# Generated by Django 5.2.1 on 2025-05-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0004_diary_created_at_diary_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='updated_at',
        ),
    ]
